### ISSUE TITLE
Bulk write failed due to previous MongoDB\\Driver\\Exception\\AuthenticationException: Authentication failed

### ISSUE THREAD

**Issue by cnizzardini** [alekitto/messenger-extra#23]
What is the proper format for `messenger.yaml`?

**Stack Trace**

```php
{
  "@context": "/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "BulkWriteException",
  "hydra:description": "Bulk write failed due to previous MongoDB\\Driver\\Exception\\AuthenticationException: Authentication failed.",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/var/www/cpic/vendor/mongodb/mongodb/src/Operation/InsertOne.php",
      "line": 134,
      "args": []
    },
    {
      "namespace": "MongoDB\\Driver",
      "short_class": "Server",
      "class": "MongoDB\\Driver\\Server",
      "type": "->",
      "function": "executeBulkWrite",
      "file": "/var/www/cpic/vendor/mongodb/mongodb/src/Operation/InsertOne.php",
      "line": 134,
      "args": [
        [
          "string",
          "itcollect.messenger"
        ],
        [
          "object",
          "MongoDB\\Driver\\BulkWrite"
        ],
        [
          "array",
          []
        ]
      ]
    },
    {
      "namespace": "MongoDB\\Operation",
      "short_class": "InsertOne",
      "class": "MongoDB\\Operation\\InsertOne",
      "type": "->",
      "function": "execute",
      "file": "/var/www/cpic/vendor/mongodb/mongodb/src/Collection.php",
      "line": 931,
      "args": [
        [
          "object",
          "MongoDB\\Driver\\Server"
        ]
      ]
    },
    {
      "namespace": "MongoDB",
      "short_class": "Collection",
      "class": "MongoDB\\Collection",
      "type": "->",
      "function": "insertOne",
      "file": "/var/www/cpic/vendor/kcs/messenger-extra/lib/Transport/Mongo/MongoSender.php",
      "line": 103,
```

YAML:

```yaml
# messenger.yaml

framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            mongo: 'mongodb://root:root@192.168.64.100:27017/mydbname?authSource=mydbname'

        routing:
            'App\Message\RebaseLineAuditMessage': mongo
```
